Add 'yarn lint' command and run it in GH actions
codimd/react-client pull request #517
Opened 2020-08-30 20:53 UTC by ErikMichelson

### Component/Part
GitHub actions CI

### Description
This PR adds an explicit `yarn lint` to call to the GitHub actions workflow as the build command obviously does no linting anymore.

### Steps

- [ ] added implementation _(not applicable)_
- [x] added / updated tests
- [ ] added / updated documentation _(not applicable)_
- [ ] extended changelog _(not applicable)_

### Related Issue(s)
none

2020-08-30 21:19 UTC, DerMolly approved these changes

2020-08-31 07:23 UTC, mrdrogdrog requested changes
You don't need to run the linter with every node version, because eslint is independent from the used node version.

2020-08-31 09:53 UTC, mrdrogdrog requested changes
Solve the linting errors

2020-08-31 10:13 UTC, mrdrogdrog approved these changes
Solved it myself

2020-08-31 10:48 UTC, merged