add vega-lite diagram
codimd/react-client pull request #574
Opened 2020-09-17 20:45 UTC by DerMolly

### Component/Part
editor -> render

### Description
This PR adds vega-lite diagrams
### Steps

- [x] added implementation
- [ ] added / updated tests
- [ ] added / updated documentation
- [x] extended changelog

### Related Issue(s)
#573

2020-09-18 12:56 UTC, ErikMichelson requested changes
Writing Vega-Lite code instantly results in an app crash, as the library throws errors as soon as an `vega-lite`-tag is detected that doesn't contain valid JSON.

2020-09-18 22:27 UTC, ErikMichelson approved these changes

2020-09-19 15:38 UTC, mrdrogdrog requested changes

2020-09-19 15:38 UTC, mrdrogdrog commented on CHANGELOG.md
> +- Code blocks with 'vega-lite' are rendered as [vega-lite diagrams](https://vega.github.io/vega-lite/examples/).
```suggestion
- Code blocks with 'vega-lite' as language are rendered as [vega-lite diagrams](https://vega.github.io/vega-lite/examples/).
```

2020-09-19 16:28 UTC, mrdrogdrog approved these changes

2020-09-19 17:34 UTC, merged